// <auto-generated />
namespace RateMyAmenity.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class newimagecolumn : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207071024477_new image column"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so1dZm39xfbzIl0V7PZb2H6XHZZERLq/z8vw9Edt5CMQ+sl1Sp6eEXHv95nqVc8efffRVk9d+C2rze+XXwQf00cu6WuV1e/0qP/feO3v6UXo3fPdu92X7auc9oPDZR2fL9t7eR+mLdVlmk5I+OM/KJv8oXX366HVb1fnn+TKviSqzl1nb5jVNz9ks5yEoKR6tPr0dNR7e3dkDNe5my2XVZi3NdQ/5CKr4zSD7uq2JdT5KnxXv8tnzfHnRzi3CX2TvzCf7OzvEQV8tC2I1equt17k/Qvl7c8+ni6wof/jdvsya5qqqZz+Enl9kl8UFz0IHB5IB6pPY/lVe8vfNvFgJ94/lu98f80INntXV4lVV2nfk89//TVZf5C0NoYp8+bpa19MONo/vOqHYKCoC6esIi7z5dcTFvfn/AYERZH8yKzHhykL0QRmwgyK8GdJJtSAt2DY/BE7s9Hy2yC5+GBI/KADK3V+X/Q2HR9nfyMZtcRFTVORxfNRQ/f5WZB1Kna96Qtn9/oPkUoF9HcHUV7+OZHqv/n9ANIHiD4GrO73+3FjP49mszptm9+es572fs57v/Zz1vP/D7/nlvFr+HLDXz5Fz9t180hTtz8F4n2et6fRptZ58DWv+vAKmHwTiaX6ercv259w6b3JP38Medq30"
                       + "kL28jT08bppqWjAyAZLqKIQDO13O0k1egxDWeRtESSJ7sSqLKXX92Uff6pFqAKK1+A4ih5qb4T2+641m8yC71B7CapD0DjHjQLzHWAcdnPck4OCAZa4pe9BmBfkNRgyyNptkTf70SW+8aP46b0Mv0nFMMAe9YYUvWwbuvW7GdAMAoQ77jT0QltgdGB4dupgYl9drEnOJu+7eDbxukfYGHOJ0M3d7MBTHrhsZDusWQ+5pkf6oN7L+rZjfw9ubqw2jH+L3m4m4gQRGo1kut989vivZMf3g8d2BNNrjL7LVCr26N/WT9LXk1E62X79/1mwhMO5OA9p2ZdL2RN49maXOtwhiZ/mzom5aI7UfpSezRa/ZzTJtOvJFuz9VRs5Ma/xupaiXVxRN0IHiyPeMRoQInAenQ7Ns3n8tRTozK7N6INt3UpXrxTL8rMttm6FIKNGFI5/eHpL6bj4Y/ej2MFyWzAfjPu1Deny3Q9Xu5HmWXVt2RKjLCrdilGH18J6solr//Zll6MUh0kr7LsO4T28/SfKOpqL6wPSL28NzCSkfmPv09pDUhfXB6Ef/r2EcZxI+mHX0z6/BO4NvDhFWX+hyj/fx7SdJ0iU+GPnk9hD6+up9dZVLYwTDsZ++N6S9KKS9rwHpXhTSva8BaT8Kaf99IGkaIFDG8tHtYXwTdsEG6D4U++Ht4XC87cPgD97jfY62AwBV32ffBCEMtn1I4Tc/fIUVupIxc2dihVuZNNM4brdirg5c4qjRCoOLPmHe296pqx3TW6CSxeI9EVTH/ZYIDvlvv7/54vaodeOA955fnUEXGG2aYmd6XPsBCxN3UiJ07AB8z7nWtwfM0+/vfX17mt4Kzfeb8W+cJW+e914Y2G1itYp+Yv+2YaCGYF/4sSGPEJEej6zRcLAbk0mTj1LC/bKYIR57fd20+WKMBuPXv6h8ndeXeX2Sj/fHO67ZF9myOM+b9k31NqewnL87LouskRD9vUJOu5zTNLMyEnCC"
                       + "zz15/DrrXHFxvXmRy7wn+Zti2aoUbVrLes/MrgvjpJPlZVZP51kdyeG+X946yNN/Y1BdnPdBgG+9uBnTTreb8yFhvXnW3Zs/i/MeBGLST51n5XvDcTHYB01IH3Cw1vA1od56mlVpf515HrQcN0+09+rP4kxL6PRBdOwD/VlRGd2V428asF0Y/qYB23Xfbxrw/jcOOFi1/cag/uwo+86a6zcG11tSPS8r/PGeIuWvqH49CLEF1a85vlsruaGw6nZ67mYfNO73DMQqN2vHXoeejnxPagd43BbMremqavzruwoKYGMQ8t4TcjOBI93eljbf4Gx9vXX1aPTXWy68xYLwbi/y/HL5NC/zNk+Pp7Lod5I102zWpwBirs39y3JvDwf5OMSjv9pNM53XsPlZSaFZ09YUnPUSOi/rYjktVlkZjrvTbAP/xKNJC7b7zdN8lS/hifTH6cnIDX1uDGRtDx1i30SOwaX8GxgpFp97E9mbwtjk/f+MiW49ncNpqJ8tBroh+2Wh/+wxj9GagviNikibBxNoP/uhcFFoniJ4xBXjN8RLZqy3mdxN9u/2HLXBHHP7r2d/fy5Y6wbV9HNt435uGes95vcbsXTvz1Y/F8auk8pVTHpp1x5PaVbe07Ifpc4vC0yfpGw/+2g2qWjSxa/ThZzOvHbBGn7oATZfxECrMNwI3CrVHnT7TQy8fInF9tthP0Aa/8vhUdyOTB3pGRrPJqIFTfo9hksCG9zr1GsZjHTjeltER9kxuo960hB3fHpvysddPRUO6X2Hq5r2puHG13J63qKHcgzZH/pQu3ZleHIHWg6j35E6f2Fv47CjPB5ZFvzmBz881bcxv98Ac3/zQ++t4NnvHt8V7aAf0J+9lToyNmt6eyHBN5m9prhwIB4TzGXOToIDatqcLc8rY/Y6GJkmnSzBF3mbzcgGHddtcZ5NW/p6SmlOHi6vRSCVOMlnZ8sv1+1q3dKQ88WkDHgJVnNT/4/v9nB+/OUKf3lL"
                       + "k19/CIRmQUPIv1w+WRflzOL9LJLaGAABc6wJfswlWfc2v7i2kF5whvY2gJR8T40X8SZfrEoC1ny5fJ1d5sO43UzDkGKPnxbZRZ0tGoXh3qc/if1mi3dH/08AAAD///pc/cf0PwAA"; }
        }
    }
}
